/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2_p2_salvadormacias;

import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author Apple
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cargarArchivo = new javax.swing.JButton();
        pg2 = new javax.swing.JProgressBar();
        pg3 = new javax.swing.JProgressBar();
        pg4 = new javax.swing.JProgressBar();
        progressbar1 = new javax.swing.JProgressBar();
        boton_simulacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cargarArchivo.setText("Cargar Archivo");
        btn_cargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cargarArchivoMouseClicked(evt);
            }
        });

        boton_simulacion.setText("iniciar simulacion");
        boton_simulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_simulacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btn_cargarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(boton_simulacion)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(progressbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pg2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pg3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pg4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargarArchivo)
                    .addComponent(boton_simulacion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_simulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_simulacionMouseClicked
        Thread progress_bar1 = new Thread(() -> {
            int cont = 0;
            while (cont <= 100) {
                int temp = cont;
                SwingUtilities.invokeLater(() -> {
                    progressbar1.setValue(temp);
                });
                try {
                    Thread.sleep(400);
                    cont++;
                } catch (Exception e) {

                }
            }
            

        });
        progress_bar1.start();

        Thread progress_bar2 = new Thread(() -> {
            int cont = 0;
            while (cont <= 100) {
                int temp = cont;
                SwingUtilities.invokeLater(() -> {
                    pg2.setValue(temp);
                });
                try {
                    Thread.sleep(300);
                    cont++;
                } catch (Exception e) {

                }
            }
        });
                progress_bar2.start();


        Thread progress_bar3 = new Thread(() -> {
            int cont = 0;
            while (cont <= 100) {
                int temp = cont;
                SwingUtilities.invokeLater(() -> {
                    pg3.setValue(temp);
                });
                try {
                    Thread.sleep(500);
                    cont++;
                } catch (Exception e) {

                }
            }
        });
                progress_bar3.start();


        Thread progress_bar4 = new Thread(() -> {
            int cont = 0;
            while (cont <= 100) {
                int temp = cont;
                SwingUtilities.invokeLater(() -> {
                    pg4.setValue(temp);
                });
                try {
                    Thread.sleep(100);
                    cont++;
                } catch (Exception e) {

                }
            }
        });
        progress_bar4.start();

    
    // TODO add your handling code here:
    }//GEN-LAST:event_boton_simulacionMouseClicked

    private void btn_cargarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarArchivoMouseClicked
        // TODO add your handling code here:
 
        
        
        JFileChooser filechooser = new JFileChooser();
        
        int op = filechooser.showSaveDialog(this);
        
        if(op == JFileChooser.APPROVE_OPTION){
            File seleccionado = filechooser.getSelectedFile();
            try{
                  FileOutputStream fs = new FileOutputStream(seleccionado);
                  ObjectOutputStream objectWritter = new ObjectOutputStream(fs);
                  objectWritter.writeObject(btn_cargarArchivo); 
                  objectWritter.close();
                  JOptionPane.showMessageDialog(this,"Se guardo el archivo");
            }catch(Exception e){
                System.out.println("Ocurrio un error ");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_cargarArchivoMouseClicked

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_simulacion;
    private javax.swing.JButton btn_cargarArchivo;
    private javax.swing.JProgressBar pg2;
    private javax.swing.JProgressBar pg3;
    private javax.swing.JProgressBar pg4;
    private javax.swing.JProgressBar progressbar1;
    // End of variables declaration//GEN-END:variables
}
